// ILI9486 COMMAND SET

// reset the display
#define COMMAND_SOFT_RESET 0x1
#define COMMAND_SOFT_RESET_RESPONSE_ROWS 0x0
#define COMMAND_SOFT_RESET_DEAD_ROWS 0x0

// get information about the display
#define COMMAND_READ_DISPLAY_INFORMATION 0x4
#define COMMAND_READ_DISPLAY_INFORMATION_RESPONSE_ROWS 0x3
#define COMMAND_READ_DISPLAY_INFORMATION_DEAD_ROWS 0x1

// read the display's status
#define COMMAND_READ_DISPLAY_STATUS 0x9
#define COMMAND_READ_DISPLAY_STATUS_RESPONSE_ROWS 0x4
#define COMMAND_READ_DISPLAY_STATUS_DEAD_ROWS 0x1

// read the display's status
#define COMMAND_READ_DISPLAY_FORMAT 0x0C
#define COMMAND_READ_DISPLAY_FORMAT_RESPONSE_ROWS 0x1
#define COMMAND_READ_DISPLAY_FORMAT_DEAD_ROWS 0x1

// put the display to sleep
#define COMMAND_SLEEP 0x10
#define COMMAND_SLEEP_RESPONSE_ROWS 0x0
#define COMMAND_SLEEP_DEAD_ROWS 0x0

// wake the display up
#define COMMAND_WAKE 0x11
#define COMMAND_WAKE_RESPONSE_ROWS 0x0
#define COMMAND_WAKE_DEAD_ROWS 0x0

// set column address (x)
#define COMMAND_DISPLAY_ON 0x29
#define COMMAND_DISPLAY_ON_RESPONSE_ROWS 0x0
#define COMMAND_DISPLAY_ON_DEAD_ROWS 0x0

// set column address (x)
#define COMMAND_SET_COLUMN_ADDRESS 0x2A
#define COMMAND_SET_COLUMN_ADDRESS_PARAMS 0x4
#define COMMAND_SET_COLUMN_ADDRESS_RESPONSE_ROWS 0x0
#define COMMAND_SET_COLUMN_ADDRESS_DEAD_ROWS 0x0

// set page address (y)
#define COMMAND_SET_PAGE_ADDRESS 0x2B
#define COMMAND_SET_PAGE_ADDRESS_PARAMS 0x4
#define COMMAND_SET_PAGE_ADDRESS_RESPONSE_ROWS 0x0
#define COMMAND_SET_PAGE_ADDRESS_DEAD_ROWS 0x0

// write to display
#define COMMAND_WRITE_DISPLAY 0x2C
#define COMMAND_WRITE_DISPLAY_RESPONSE_ROWS 0x0
#define COMMAND_WRITE_DISPLAY_DEAD_ROWS 0x0

// read display
#define COMMAND_READ_DISPLAY 0x2E
#define COMMAND_READ_DISPLAY_RESPONSE_ROWS 0x0
#define COMMAND_READ_DISPLAY_DEAD_ROWS 0x1

// set memory access control
#define COMMAND_SET_MADCTL 0x36
#define COMMAND_SET_MADCTL_PARAMS 0x01
#define COMMAND_SET_MADCTL_RESPONSE_ROWS 0x0
#define COMMAND_SET_MADCTL_DEAD_ROWS 0x0

// set bpp of interface
#define COMMAND_SET_PIXEL_FORMAT 0x3A
#define COMMAND_SET_PIXEL_FORMAT_PARAMS 0x01
#define COMMAND_SET_PIXEL_FORMAT_RESPONSE_ROWS 0x0
#define COMMAND_SET_PIXEL_FORMAT_DEAD_ROWS 0x0
