# AVR_GCC = ${ARDUINO_DIR}/hardware/tools/avr/bin/avr-gcc
# AVR_LD = ${ARDUINO_DIR}/hardware/tools/avr/bin/avr-ld
# CFLAGS = -MMD -c -D__PROG_TYPES_COMPAT__ -mmcu=${BOARD_SUB} -DF_CPU=${CPU_SPEED} -DARDUINO=1813 -DARDUINO_ARCH_AVR   -Wall -ffunction-sections -fdata-sections -Os -std=gnu11 -fno-fat-lto-objects -fdiagnostics-color=always
# INCLD = -I${ARDUINO_DIR}/hardware/arduino/avr/cores/arduino -I${ARDUINO_DIR}/hardware/arduino/avr/cores/arduino/api -I${ARDUINO_DIR}/hardware/arduino/avr/variants/standard
#
# OUTPUT_DIR = ./build
#
# libILI9486.o : ./*.c
# 	mkdir -p ${OUTPUT_DIR}
# 	${AVR_GCC} ${CFLAGS} ${INCLD} $^
# 	mv ./*.o ${OUTPUT_DIR}/
# 	mv ./*.d ${OUTPUT_DIR}/
# 	${AVR_LD} -r -o ${OUTPUT_DIR}/$@ ${OUTPUT_DIR}/*.o
